### ISSUE TITLE
cant install also, I use debian 10 x64 digitalocean

### ISSUE THREAD

**Issue by mlopez119** [xiihaiqal/AutoScriptVPS#11]
same cant install bos
![Screenshot 2021-07-09 232328](https://user-images.githubusercontent.com/82475090/125119532-cfb85080-e123-11eb-9620-136aac039e5f.png)

**Comment by xiihaiqal** [comment]
Run this command "rm AutoScript"
Then try install it again

**Comment by mlopez119** [comment]
ok I try

**Comment by mlopez119** [comment]
same cant
![Screenshot 2021-07-09 232328](https://user-images.githubusercontent.com/82475090/125120274-d0051b80-e124-11eb-896b-42eccf24dc14.png)

**Comment by mlopez119** [comment]
![Screenshot 2021-07-09 232328](https://user-images.githubusercontent.com/82475090/125120362-ef9c4400-e124-11eb-9724-6d0e8c2098b4.png)

**Comment by xiihaiqal** [comment]
Run this command "rm AutoScript" and install the script again

**Comment by mlopez119** [comment]
done.. thank you very much

**Comment by mlopez119** [comment]
already worked
