### ISSUE TITLE
Only 1 user can be connected

### ISSUE THREAD

**Issue by bugrevealingbme** [xiihaiqal/AutoScriptVPS#18]
There is only 1 connection from 1 user. I want a lot of links from 1 user.

**Comment by xiihaiqal** [comment]
type this "nano /etc/openvpn/server_tcp.conf"
add "duplicate-cn"
then save and reboot your server

**Comment by bugrevealingbme** [comment]
Thank you so much

**Comment by bugrevealingbme** [comment]
Not working very well? Any another method?

**Comment by xiihaiqal** [comment]
nope that mothod should work
