### ISSUE TITLE
error: Required dependency 'netstat' is missing.

### ISSUE THREAD

**Issue by AfandiFx** [xiihaiqal/AutoScriptVPS#5]
it says: 
error: Required dependency 'netstat' is missing.
Autoinstall dependencies by 'apt-get'? (n to exit)
![image](https://user-images.githubusercontent.com/73357591/102925355-2d5db600-44ce-11eb-9dd0-63ba72c574eb.png)

**Comment by xiihaiqal** [comment]
just click enter
