### ISSUE TITLE
Usage user ovpn

### ISSUE THREAD

**Issue by mlopez119** [xiihaiqal/AutoScriptVPS#7]
Hi brother, can you make option to track usage how much quota gb user use?

**Comment by malikshi** [comment]
@mlopez119 it needs a different approach for it I think, try this one
https://github.com/Chocobozzz/OpenVPN-Admin

**Comment by mlopez119** [comment]
Oh ok. Thanks brother

**Comment by xiihaiqal** [comment]
if you want to track usage...you can use openvpn monitor...it already install in the script
