### ISSUE TITLE
Cannot connect to internet

### ISSUE THREAD

**Issue by mohdmin** [xiihaiqal/AutoScriptVPS#8]
Openvpn app shows vpn connected but i can't browse internet. No internet.

**Comment by xiihaiqal** [comment]
provider?

**Comment by mohdmin** [comment]
Linode

**Comment by mohdmin** [comment]
> provider?

Linode

**Comment by xiihaiqal** [comment]
try this command, "bash /etc/openvpn/openvpn.bash"

**Comment by mohdmin** [comment]
> try this command, "bash /etc/openvpn/openvpn.bash"

Solved. A lot of thanks. 👍👍👍
